version: '3.8'

services:
  db:
    container_name: quartz-database-container
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - "../my_sql_data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"    # copy create quartz database script
    ports:
      - 3306:3306
    networks:
      - quartz-server-network

networks:
  quartz-server-network:
    driver: bridge